### ISSUE TITLE
[Mixer] Fix 'Meter'

### ISSUE THREAD

**Issue by artiphishle** [artiphishle/daw#44]
In the mixer, the louder tracks have a quieter meter, -5 is louder than -17 as an example.
The master should be the sum of all the tracks, this wasn't done yet either.

**Acceptance Criteria**

- All the mixer tracks show correct meter's

**Comment by scha-ch** [comment]
Will be replaced with Frequency Analyzer

**Comment by scha-ch** [comment]
Tone.Meter's value is by default set to dbfs (decibel) which is rather unconvenient to calc with, the solution here is to set format to value range 0-1 instead.

`meter.normalRange = true`
