### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [artiphishle/daw#97]
Hi there, 1st of all thanks for this awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [DAWs page](https://github.com/forart/HyMPS/blob/main/DAWs.md#--) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/DAWs.md#generic-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/artiphishle/daw/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/artiphishle/daw/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by artiphishle** [comment]
Thank you, I've forgot to add the license.

[PR which added the MIT license](https://github.com/artiphishle/daw/pull/99)

I guess that row in the package.json is all it needs, otherwise let me know, thanks.

BTW: I'm looking for contributers, so if you'd like to work on the 'official' repo, be my guest! Also if you like to mention 'artiphishle' (Github or Instagram account with same name) it would be very appreciated, but it's MIT and your choice in the end. Thank you very much!

**Comment by forart** [comment]
Thanks for your reply.

As you can see from the badge (that's a "litmus test"), the license needs to be set through the GH wizard or it won't be recognized.

ANW: our "collection" is made with the scope of favouring collaborations between developers just because we unfortunately don't have anyone in our staff that can technically contribute to projects, sorry.

ANW2: we have some collaborators that can provide you audio engineering techniques and direct connections to resources, if you like. Let's keep in touch.

**Comment by artiphishle** [comment]
Sorry for the delay. The LICENSE file is now added correctly and displayed as MIT license.

Yes, keep me posted & enjoy music!
